apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: payment-app
  namespace: argocd
spec:
  project: payment
  source:
    repoURL: git@github.com:jojo-saritrat/nonprod-k8s-manifests.git
    targetRevision: main
    path: dev/payment
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      enabled: true
      prune: true
      allowEmpty: true
      selfHeal: true