apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cart
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
spec:
  description: Cart Team
  destinations:
  - name: '*'
    namespace: '*'
    server: '*'  
  clusterResourceWhitelist:
  - group: ""
    kind: Namespace
  roles:
  - description: Read Only
    name: read-only
    policies:
    - p, proj:ecommerce:read-only, applications, get, ecommerce/*, allow
  - description: Read Write
    name: read-write   
    policies:
    - p, proj:ecommerce:read-write, applications, get, ecommerce/*, allow
    - p, proj:ecommerce:read-write, applications, sync, ecommerce/*, allow
    - p, proj:ecommerce:read-write, applications, update, ecommerce/*, allow        
  sourceRepos:
  - git@github.com:jojo-saritrat/nonprod-k8s-manifests.git
  - xxx/cart
  - xxx/payment
  
