apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cart-config
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:jojo-saritrat/nonprod-k8s-config.git
    targetRevision: main
    path: dev/cart
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      enabled: true
      prune: true
      allowEmpty: true
      selfHeal: true