apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
spec:
  description: Infrastructure resources
  roles:
  - description: Read Only
    name: read-only
    policies:
    - p, proj:infra:read-only, applications, get, infra/*, allow
  clusterResourceWhitelist:
  - group: ""
    kind: Namespace
  destinations:
  - name: '*'
    namespace: '*'
    server: '*'  
  sourceRepos:
  - https://github.com/kostis-codefresh/*
